print("Hello World!")
print("Hello Again!")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("I can't believe im doing this again...")
#print("You are a failure!")
